import {
  ReviewBundleError, loadReviewBundle, exportReviewedBundle, finalizeBundle,
  resolveUnresolvedQuestion, rejectUnresolvedQuestion, sha256Hex, detectImageType,
  PRODUCTION_LIMITS
} from './core.js';

let bundle = null;
let visibleCases = [];
let index = 0;
let revealAnswers = false;
let coverageMode = false;
let objectUrls = [];

const $ = (id) => document.getElementById(id);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blocking = (warnings=[]) => warnings.filter(w=>w.severity==='blocking');
const caseMeta = id => bundle.reviewMap.cases.find(x=>x.caseId===id);
const manifestCase = id => bundle.manifest.cases.find(x=>x.id===id);
const asset = id => bundle.manifest.assets.find(x=>x.id===id);
const prompt = id => bundle.manifest.questionPrompts.find(x=>x.id===id);
const caseQuestion = id => bundle.manifest.caseQuestions.find(x=>x.id===id);
const caseAssets = id => bundle.manifest.caseAssets.filter(x=>x.caseId===id).sort((a,b)=>a.displayOrder-b.displayOrder);
const caseQuestions = id => bundle.manifest.caseQuestions.filter(x=>x.caseId===id);

function clearUrls(){ for(const url of objectUrls) URL.revokeObjectURL(url); objectUrls=[]; }
function blobUrl(bytes,type='image/jpeg'){const url=URL.createObjectURL(new Blob([bytes],{type}));objectUrls.push(url);return url;}
function download(bytes,name,type='application/zip'){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function errorText(error){return error instanceof ReviewBundleError ? error.issues.join('\n') : String(error?.message ?? error);}
function showErrors(title, errors){$('errors').innerHTML=`<div class="error-card"><strong>${esc(title)}</strong><ul>${errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;$('errors').scrollIntoView({behavior:'smooth',block:'nearest'});}
function clearErrors(){$('errors').innerHTML='';}

async function openDb(){return await new Promise((resolve,reject)=>{const req=indexedDB.open('flashcards-slide-review',1);req.onupgradeneeded=()=>req.result.createObjectStore('bundles',{keyPath:'bundleId'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function persist(){if(!bundle)return;try{const db=await openDb();const media=[];for(const [path,bytes] of bundle.files)if(path.startsWith('media/'))media.push([path,bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)]);const tx=db.transaction('bundles','readwrite');tx.objectStore('bundles').put({bundleId:bundle.reviewMap.bundleId,manifest:bundle.manifest,reviewMap:bundle.reviewMap,media,updatedAt:Date.now()});await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error);});db.close();$('persist').textContent='Saved locally';}catch(e){$('persist').textContent='Local save failed';}}
async function restorePersisted(loaded){try{const db=await openDb();const tx=db.transaction('bundles');const req=tx.objectStore('bundles').get(loaded.reviewMap.bundleId);const saved=await new Promise((r,j)=>{req.onsuccess=()=>r(req.result);req.onerror=()=>j(req.error);});db.close();if(saved){loaded.manifest=saved.manifest;loaded.reviewMap=saved.reviewMap;for(const [path,buffer] of saved.media)loaded.files.set(path,new Uint8Array(buffer));}}catch{}return loaded;}

function counts(){const c={all:bundle.reviewMap.cases.length,pending:0,approved:0,needs_review:0,rejected:0,blocking:0,low:0,missing:0,image:0,unresolved:bundle.reviewMap.unresolvedQuestions.filter(x=>x.reviewStatus!=='rejected'&&!x.resolvedCaseQuestionId).length};for(const x of bundle.reviewMap.cases){c[x.reviewStatus]++;if(x.confidence==='low')c.low++;if(blocking(x.warnings).length||x.assets.some(a=>blocking(a.warnings).length)||x.questions.some(q=>blocking(q.warnings).length))c.blocking++;if(x.assets.some(a=>a.warnings.length))c.image++;}for(const u of bundle.reviewMap.unresolvedQuestions)if(u.warnings.some(w=>w.code==='missing_answer')&&u.reviewStatus!=='rejected')c.missing++;return c;}
function refreshFilters(){const c=counts();for(const [k,v] of Object.entries(c)){const el=$(`count-${k}`);if(el)el.textContent=v;}}
function applyFilter(){if(!bundle)return;const f=$('filter').value;visibleCases=bundle.reviewMap.cases.filter(c=>{if(f==='all')return true;if(['pending','approved','needs_review','rejected'].includes(f))return c.reviewStatus===f;if(f==='blocking')return blocking(c.warnings).length||c.assets.some(a=>blocking(a.warnings).length)||c.questions.some(q=>blocking(q.warnings).length);if(f==='low')return c.confidence==='low'||c.assets.some(a=>a.confidence==='low')||c.questions.some(q=>q.confidence==='low');if(f==='missing')return bundle.reviewMap.unresolvedQuestions.some(u=>u.caseId===c.caseId&&u.reviewStatus!=='rejected'&&u.warnings.some(w=>w.code==='missing_answer'));if(f==='image')return c.assets.some(a=>a.warnings.length);if(f==='unresolved')return bundle.reviewMap.unresolvedQuestions.some(u=>u.caseId===c.caseId&&!['rejected'].includes(u.reviewStatus)&&!u.resolvedCaseQuestionId);return true;});index=Math.min(index,Math.max(0,visibleCases.length-1));render();}

function warningHtml(warnings){if(!warnings?.length)return'';return `<div class="warnings">${warnings.map(w=>`<div class="warn ${esc(w.severity)}"><b>${esc(w.severity)}</b> · ${esc(w.code)} — ${esc(w.message)}</div>`).join('')}</div>`;}
function refsHtml(refs){if(!refs?.length)return '<span class="muted">No source reference</span>';return refs.map(r=>`${esc(r.sourceId)} p.${r.pages.join(', ')}`).join('; ');}
function statusSelect(kind,id,value){return `<select data-status-kind="${kind}" data-status-id="${esc(id)}"><option ${value==='pending'?'selected':''}>pending</option><option ${value==='approved'?'selected':''}>approved</option><option ${value==='needs_review'?'selected':''}>needs_review</option><option ${value==='rejected'?'selected':''}>rejected</option></select>`;}

function sourcePanel(meta){const refs=meta.sourceRefs;const pages=[];for(const r of refs)for(const p of r.pages){const cov=bundle.reviewMap.sourceCoverage.find(x=>x.sourceId===r.sourceId&&x.page===p);if(cov?.previewPath&&bundle.files.has(cov.previewPath))pages.push({r,p,cov,url:blobUrl(bundle.files.get(cov.previewPath),'image/jpeg')});}
  return `<section class="panel"><h2>Original source</h2><div class="source-meta"><b>Confidence:</b> ${esc(meta.confidence)}<br><b>Boundary notes:</b> ${esc(meta.caseBoundaryNotes||'—')}</div>${warningHtml(meta.warnings)}<div class="thumbs">${pages.map((x,i)=>`<button class="thumb ${i===0?'selected':''}" data-preview="${esc(x.cov.previewPath)}"><img src="${x.url}" alt="Source preview"><span>${esc(x.r.sourceId)} · ${x.p}</span></button>`).join('')||'<p class="muted">No linked source previews.</p>'}</div><div id="source-large">${pages[0]?`<img class="source-large" src="${pages[0].url}" alt="Selected source page"><p>${esc(pages[0].r.sourceId)} · page/slide ${pages[0].p}</p>`:''}</div></section>`;}

function proposedPanel(c,meta){const cas=manifestCase(c.caseId);const casAssets=caseAssets(c.caseId);const qs=caseQuestions(c.caseId);const unresolved=bundle.reviewMap.unresolvedQuestions.filter(u=>u.caseId===c.caseId&&!u.resolvedCaseQuestionId);
return `<section class="panel"><div class="row between"><h2>Proposed import</h2><span class="badge ${esc(meta.reviewStatus)}">${esc(meta.reviewStatus)}</span></div>
<label>Admin-only title<input data-edit="case.title" value="${esc(cas.title||'')}"></label>
<label>Vignette<textarea data-edit="case.vignetteMd" rows="6">${esc(cas.vignetteMd||'')}</textarea></label>
<h3>Fixed learner images</h3><div class="asset-grid">${casAssets.map(rel=>assetCard(rel,meta.assets.find(a=>a.assetId===rel.assetId))).join('')||'<p class="muted">No learner images.</p>'}</div>
<div class="row between"><h3>Case questions</h3><button id="toggle-answers" class="secondary">${revealAnswers?'Hide answers':'Reveal answers'}</button></div>${qs.map(q=>questionCard(q,meta.questions.find(x=>x.caseQuestionId===q.id))).join('')||'<p class="muted">No emitted questions.</p>'}
${unresolved.length?`<h3>Unresolved source questions</h3>${unresolved.map(unresolvedCard).join('')}`:''}
</section>`;}

function assetCard(rel,meta){const a=asset(rel.assetId);if(!a)return`<div class="card error-card">Missing Asset ${esc(rel.assetId)}</div>`;const bytes=bundle.files.get(a.path);const url=bytes?blobUrl(bytes,a.mimeType):'';return `<article class="card asset-card" data-asset="${esc(a.id)}"><div class="row between"><b>${esc(a.originalFilename||a.id)}</b>${meta?statusSelect('asset',a.id,meta.reviewStatus):'<span class="danger">Missing review metadata</span>'}</div>${url?`<img class="learner-image" src="${url}" alt="${esc(a.altText||'')}">`:'<div class="danger">Missing media</div>'}<div class="small">Source: ${refsHtml(meta?.sourceRefs)} · extraction: ${esc(meta?.extractionMethod||'—')} · confidence: ${esc(meta?.confidence||'—')}<br>SHA-256: <code>${esc(meta?.sha256||'missing')}</code></div>${warningHtml(meta?.warnings)}
<label>Filename<input data-asset-field="originalFilename" value="${esc(a.originalFilename||'')}"></label><label>Alt text<input data-asset-field="altText" value="${esc(a.altText||'')}"></label><label>Source label<input data-asset-field="sourceLabel" value="${esc(a.sourceLabel||'')}"></label><label>Source URL<input data-asset-field="sourceUrl" value="${esc(a.sourceUrl||'')}"></label><label>Licence<input data-asset-field="licence" value="${esc(a.licence||'')}"></label><label>Caption<textarea data-rel-field="captionMd">${esc(rel.captionMd||'')}</textarea></label><label>Display order<input type="number" min="0" data-rel-field="displayOrder" value="${rel.displayOrder}"></label><button class="secondary replace-image" data-id="${esc(a.id)}">Replace image</button><input hidden type="file" accept="image/jpeg,image/png" data-replace="${esc(a.id)}"></article>`;}

function questionCard(q,meta){const p=prompt(q.questionPromptId);return `<article class="card question-card" data-question="${esc(q.id)}"><div class="row between"><b>${esc(q.id)}</b>${meta?statusSelect('question',q.id,meta.reviewStatus):'<span class="danger">Missing review metadata</span>'}</div><div class="small">Prompt source: ${refsHtml(meta?.promptSourceRefs)}<br>Answer source: ${refsHtml(meta?.answerSourceRefs)}<br>Confidence: ${esc(meta?.confidence||'—')}</div>${warningHtml(meta?.warnings)}<label>Prompt<textarea data-question-field="promptMd">${esc(p?.promptMd||'')}</textarea></label><label class="answer ${revealAnswers?'':'hidden'}">Answer<textarea data-question-field="answerMd">${esc(q.answerMd||'')}</textarea></label></article>`;}
function unresolvedCard(u){return `<article class="card unresolved" data-unresolved="${esc(u.candidateId)}"><div class="row between"><b>${esc(u.candidateId)}</b><span class="badge ${esc(u.reviewStatus)}">${esc(u.reviewStatus)}</span></div><div class="small">Prompt source: ${refsHtml(u.promptSourceRefs)}<br>Answer source: ${refsHtml(u.answerSourceRefs)} · confidence: ${esc(u.confidence)}</div>${warningHtml(u.warnings)}<label>Prompt<textarea data-u-prompt>${esc(u.proposedPrompt)}</textarea></label><label>Answer<textarea data-u-answer placeholder="Required to include"></textarea></label><div class="row"><button class="resolve-u">Create Prompt + Case Question</button><button class="secondary reject-u">Reject unresolved question</button></div></article>`;}

function renderCoverage(){clearUrls();const rows=bundle.reviewMap.sourceCoverage.map(x=>{const source=bundle.reviewMap.sourceFiles.find(s=>s.sourceId===x.sourceId);const broken=x.caseIds.some(id=>!manifestCase(id));const missing=x.previewPath&&!bundle.files.has(x.previewPath);const issue=x.classification==='uncertain'||!x.classification||missing||broken;return `<tr class="${issue?'issue':''}"><td>${esc(source?.filename||x.sourceId)}</td><td>${x.page}</td><td>${esc(x.classification||'missing')}</td><td>${esc(x.caseIds.join(', ')||'—')}</td><td>${esc(x.notes||'')}</td><td>${x.previewPath?(missing?'missing':'present'):'none'}</td></tr>`;}).join('');$('workspace').innerHTML=`<section class="coverage"><div class="row between"><h2>Source coverage</h2><button id="back-cases">Back to Case review</button></div><table><thead><tr><th>Source</th><th>Page</th><th>Classification</th><th>Cases</th><th>Notes</th><th>Preview</th></tr></thead><tbody>${rows}</tbody></table></section>`;$('back-cases').onclick=()=>{coverageMode=false;render();};}

function render(){if(!bundle)return;if(coverageMode){renderCoverage();return;}clearUrls();refreshFilters();if(!visibleCases.length){$('workspace').innerHTML='<div class="empty">No Cases match this filter.</div>';return;}const meta=visibleCases[index];$('position').textContent=`Case ${index+1} of ${visibleCases.length}`;$('workspace').innerHTML=`<div class="review-grid">${sourcePanel(meta)}${proposedPanel(meta,meta)}</div>`;wireCurrent();}

function wireCurrent(){const meta=visibleCases[index],cas=manifestCase(meta.caseId);$('toggle-answers').onclick=()=>{revealAnswers=!revealAnswers;render();};for(const el of document.querySelectorAll('[data-edit]'))el.onchange=async()=>{if(el.dataset.edit==='case.title')cas.title=el.value;else cas.vignetteMd=el.value||null;await persist();};
for(const card of document.querySelectorAll('[data-asset]')){const id=card.dataset.asset,a=asset(id),rel=bundle.manifest.caseAssets.find(x=>x.caseId===meta.caseId&&x.assetId===id);for(const el of card.querySelectorAll('[data-asset-field]'))el.onchange=async()=>{a[el.dataset.assetField]=el.value||null;await persist();};for(const el of card.querySelectorAll('[data-rel-field]'))el.onchange=async()=>{rel[el.dataset.relField]=el.dataset.relField==='displayOrder'?Number(el.value):el.value||null;await persist();render();};const btn=card.querySelector('.replace-image'),input=card.querySelector('[data-replace]');btn.onclick=()=>input.click();input.onchange=async()=>replaceImage(id,input.files?.[0]);}
for(const card of document.querySelectorAll('[data-question]')){const q=caseQuestion(card.dataset.question),p=prompt(q.questionPromptId);for(const el of card.querySelectorAll('[data-question-field]'))el.onchange=async()=>{if(el.dataset.questionField==='promptMd')p.promptMd=el.value;else q.answerMd=el.value;await persist();};}
for(const s of document.querySelectorAll('[data-status-kind]'))s.onchange=async()=>{const kind=s.dataset.statusKind,id=s.dataset.statusId;const target=kind==='asset'?meta.assets.find(x=>x.assetId===id):meta.questions.find(x=>x.caseQuestionId===id);target.reviewStatus=s.value;await persist();refreshFilters();};
for(const card of document.querySelectorAll('[data-unresolved]')){const id=card.dataset.unresolved;card.querySelector('.resolve-u').onclick=async()=>{try{resolveUnresolvedQuestion(bundle.manifest,bundle.reviewMap,id,{promptMd:card.querySelector('[data-u-prompt]').value,answerMd:card.querySelector('[data-u-answer]').value});await persist();render();}catch(e){showErrors('Cannot resolve question',[errorText(e)]);}};card.querySelector('.reject-u').onclick=async()=>{rejectUnresolvedQuestion(bundle.reviewMap,id);await persist();render();};}
for(const thumb of document.querySelectorAll('.thumb'))thumb.onclick=()=>{const path=thumb.dataset.preview,bytes=bundle.files.get(path);if(!bytes)return;document.querySelectorAll('.thumb').forEach(x=>x.classList.remove('selected'));thumb.classList.add('selected');$('source-large').innerHTML=`<img class="source-large" src="${blobUrl(bytes,'image/jpeg')}" alt="Selected source page">`;};}

async function replaceImage(assetId,file){clearErrors();try{if(!file)return;if(!['image/jpeg','image/png'].includes(file.type))throw new ReviewBundleError('Replacement must be JPEG or PNG.');if(file.size<=0||file.size>PRODUCTION_LIMITS.maxImageBytes)throw new ReviewBundleError(`Replacement image must be 1-${PRODUCTION_LIMITS.maxImageBytes} bytes.`);const bytes=new Uint8Array(await file.arrayBuffer()),detected=detectImageType(bytes);if(detected!==file.type)throw new ReviewBundleError('Replacement image bytes do not match the selected MIME type.');const a=asset(assetId),meta=bundle.reviewMap.cases.flatMap(c=>c.assets).find(x=>x.assetId===assetId);bundle.files.set(a.path,bytes);a.mimeType=file.type;a.originalFilename=file.name;meta.sha256=await sha256Hex(bytes);meta.extractionMethod='human_replacement';meta.reviewStatus='needs_review';await persist();render();}catch(e){showErrors('Image replacement failed',[errorText(e)]);}}

async function approveCurrent(){clearErrors();const meta=visibleCases[index];for(const a of meta.assets)if(a.reviewStatus!=='rejected'&&!blocking(a.warnings).length)a.reviewStatus='approved';for(const q of meta.questions)if(q.reviewStatus!=='rejected'&&!blocking(q.warnings).length)q.reviewStatus='approved';const unresolved=bundle.reviewMap.unresolvedQuestions.filter(u=>u.caseId===meta.caseId&&!u.resolvedCaseQuestionId&&u.reviewStatus!=='rejected');const why=[];if(blocking(meta.warnings).length)why.push(...blocking(meta.warnings).map(x=>x.message));for(const a of meta.assets)if(a.reviewStatus!=='approved')why.push(`Image ${a.assetId} still needs review.`);for(const q of meta.questions)if(q.reviewStatus!=='approved')why.push(`Question ${q.caseQuestionId} still needs review.`);for(const u of unresolved)why.push(`Unresolved question ${u.candidateId} is not resolved/rejected.`);const c=manifestCase(meta.caseId);if(!String(c.title||'').trim())why.push('Case title is blank.');if(!c.primaryTopicId)why.push('Primary Topic is missing.');if(why.length){meta.reviewStatus='needs_review';await persist();showErrors('Cannot approve Case',why);render();return;}meta.reviewStatus='approved';await persist();render();}
async function setCaseStatus(status){const meta=visibleCases[index];meta.reviewStatus=status;await persist();render();}

async function loadFile(file){clearErrors();try{bundle=await restorePersisted(await loadReviewBundle(file));visibleCases=bundle.reviewMap.cases.slice();index=0;coverageMode=false;$('empty-start').hidden=true;$('review-shell').hidden=false;$('batch').textContent=bundle.reviewMap.batchName;applyFilter();await persist();}catch(e){showErrors('Could not open review bundle',errorText(e).split('\n'));}}

$('zip-input').onchange=e=>loadFile(e.target.files?.[0]);const drop=$('drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');loadFile(e.dataTransfer.files?.[0]);};
$('prev').onclick=()=>{if(index>0){index--;render();}};$('next').onclick=()=>{if(index<visibleCases.length-1){index++;render();}};$('approve').onclick=approveCurrent;$('needs').onclick=()=>setCaseStatus('needs_review');$('reject').onclick=()=>setCaseStatus('rejected');$('filter').onchange=applyFilter;$('coverage').onclick=()=>{coverageMode=true;render();};
$('export-reviewed').onclick=()=>{try{download(exportReviewedBundle(bundle),`${bundle.reviewMap.batchName.replace(/[^A-Za-z0-9._-]+/g,'-')}-reviewed.zip`);}catch(e){showErrors('Export failed',[errorText(e)]);}};
$('finalize').onclick=async()=>{clearErrors();try{const out=await finalizeBundle(bundle);download(out.zip,'flashcards-import-v1.zip');}catch(e){showErrors('Finalization blocked',e instanceof ReviewBundleError?e.issues:[errorText(e)]);}};

document.addEventListener('keydown',e=>{if(!bundle)return;const t=e.target;if(t?.matches?.('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='ArrowLeft'){e.preventDefault();$('prev').click();}else if(e.key==='ArrowRight'){e.preventDefault();$('next').click();}else if(e.key===' '){e.preventDefault();revealAnswers=!revealAnswers;render();}else if(e.key.toLowerCase()==='a')approveCurrent();else if(e.key.toLowerCase()==='r')setCaseStatus('needs_review');else if(e.key.toLowerCase()==='x')setCaseStatus('rejected');});
